export default {
  WIDGET_CONTAINER: 'WIDGET_CONTAINER',
  DATA_DISPLAY_IMAGE:'DATA_DISPLAY_IMAGE',
  FORM_INPUT: 'FORM_INPUT',
  FORM_SELECT: 'FORM_SELECT',
  FORM_SWITCH: 'FORM_SWITCH',
  FORM_TIME_PICKER: 'FORM_TIME_PICKER'
}
