export default {
  WIDGET_CONTAINER: 'WIDGET_CONTAINER',
  // data display
  DATA_DISPLAY_IMAGE:'DATA_DISPLAY_IMAGE',
  DATA_DISPLAY_CAROUSEL:'DATA_DISPLAY_CAROUSEL',
  DATA_DISPLAY_Table:'DATA_DISPLAY_Table',
}
