export default {
  // container
  WIDGET_CONTAINER: 'WIDGET_CONTAINER',
  GRID_CONTAINER: 'GRID_CONTAINER',
  // data display
  DATA_DISPLAY_IMAGE: 'DATA_DISPLAY_IMAGE',
  DATA_DISPLAY_CAROUSEL: 'DATA_DISPLAY_CAROUSEL',
  DATA_DISPLAY_TABLE: 'DATA_DISPLAY_TABLE',
  DATA_DISPLAY_DESCRIPTION: 'DATA_DISPLAY_DESCRIPTION',
  // data entry
  DATA_ENTRY_FORM: 'DATA_ENTRY_FORM',
  // chart
  CHART_RAW: 'CHART_RAW',
  CHART_LINE: 'CHART_LINE',
  // rich text
  CUSTOM_RICH_TEXT: 'CUSTOM_RICH_TEXT'
}
